development:
  adapter: mysql2
  pool: 20
  reconnect: false
  encoding: utf8
  database: etidoma
  username: root
  password: Nocturnal2802
  host: 127.0.0.1
  port: 3306
  #socket: /var/run/tmp/mysql.sock

test:
  adapter: mysql2
  pool: 20
  reconnect: false
  encoding: utf8
  database: etidoma
  username: root
  password: Nocturnal2802
  host: 127.0.0.1
  port: 3306
  #socket: /var/run/tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  database: etidoma
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
  host:   <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:   <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
